const mongoose = require('mongoose');

const TASK_TEAMS = Object.freeze(['OPERATIONS', 'SALES', 'COMPLIANCE', 'FINANCE', 'LEGAL', 'DOCUMENTATION', 'SUPPORT']);
const TASK_PRIORITIES = Object.freeze(['LOW', 'MEDIUM', 'HIGH', 'URGENT']);
const TASK_STATUSES = Object.freeze(['OPEN', 'IN_PROGRESS', 'DONE', 'CANCELLED']);

const taskSchema = new mongoose.Schema(
  {
    taskCode: {
      type: String,
      unique: true,
      sparse: true,
      index: true,
    },
    legacyTaskCode: { type: String, default: null, index: true },
    legacyCode: { type: String, default: null, index: true },
    order: { type: mongoose.Schema.Types.ObjectId, ref: 'PortalOrder', required: true, index: true },
    client: { type: mongoose.Schema.Types.ObjectId, ref: 'PortalClient', index: true },
    assignedTo: { type: mongoose.Schema.Types.ObjectId, ref: 'PortalUser', default: null },
    title: { type: String, required: true, trim: true },
    description: { type: String, trim: true },
    team: { type: String, enum: TASK_TEAMS, required: true },
    priority: { type: String, enum: TASK_PRIORITIES, default: 'MEDIUM' },
    dueDate: { type: Date },
    status: { type: String, enum: TASK_STATUSES, default: 'OPEN', index: true },
    completedAt: { type: Date },
    completedBy: { type: mongoose.Schema.Types.ObjectId, ref: 'PortalUser' },
    notes: { type: String, trim: true },
    autoGenerated: { type: Boolean, default: false },
    triggerStatus: { type: String },
  },
  { timestamps: true, collection: 'portal_tasks' }
);

taskSchema.index({ status: 1, team: 1 });
taskSchema.index({ dueDate: 1, status: 1 });
taskSchema.index({ assignedTo: 1, status: 1 });

module.exports = mongoose.model('PortalTask', taskSchema);
module.exports.TASK_TEAMS = TASK_TEAMS;
module.exports.TASK_PRIORITIES = TASK_PRIORITIES;
module.exports.TASK_STATUSES = TASK_STATUSES;
