'use strict';

const { Task, Order } = require('../../models/portal');
const AppError = require('../../utils/portal/AppError');
const { logAudit } = require('./auditLog.service');
const { AUDIT_ACTIONS } = require('../../constants/portal/auditActions');
const { generateTaskCode } = require('./idGenerator.service');
const { ORDER_STATUS } = require('../../constants/portal/orderStatus');

// Auto-task definitions keyed by order toStatus.
// Each entry is { title, description, team, priority, dueDaysFromNow }.
const AUTO_TASKS = {
  [ORDER_STATUS.PAYMENT_CONFIRMED]: {
    title: 'Verify Payment and Assign Admin',
    description: 'Payment confirmed by system. Verify receipt and assign this order to an admin for processing.',
    team: 'FINANCE',
    priority: 'HIGH',
    dueDaysFromNow: 1,
  },
  [ORDER_STATUS.KYC_SUBMITTED]: {
    title: 'Review Submitted KYC Documents',
    description: 'Client has submitted KYC documents. Begin compliance review and request additional docs if needed.',
    team: 'COMPLIANCE',
    priority: 'HIGH',
    dueDaysFromNow: 2,
  },
  [ORDER_STATUS.KYC_VERIFICATION]: {
    title: 'Verify KYC Documents',
    description: 'KYC documents are under verification. Complete verification and approve or reject.',
    team: 'COMPLIANCE',
    priority: 'URGENT',
    dueDaysFromNow: 1,
  },
  [ORDER_STATUS.IN_PROGRESS]: {
    title: 'Process Order and Deliver Service',
    description: 'KYC verified. Begin service delivery and processing for this order.',
    team: 'OPERATIONS',
    priority: 'MEDIUM',
    dueDaysFromNow: 7,
  },
  [ORDER_STATUS.KYC_REJECTED]: {
    title: 'Notify Client of KYC Rejection',
    description: 'KYC documents have been rejected. Contact client to explain required corrections.',
    team: 'SUPPORT',
    priority: 'HIGH',
    dueDaysFromNow: 1,
  },
  [ORDER_STATUS.QUALITY_CHECK]: {
    title: 'Perform Quality Check',
    description: 'Service processing complete. Perform quality review before marking order as Completed.',
    team: 'OPERATIONS',
    priority: 'HIGH',
    dueDaysFromNow: 1,
  },
  [ORDER_STATUS.COMPLETED]: {
    title: 'Prepare Delivery Package',
    description: 'Order completed. Prepare documents and delivery package for the client.',
    team: 'DOCUMENTATION',
    priority: 'HIGH',
    dueDaysFromNow: 2,
  },
  [ORDER_STATUS.DELIVERED]: {
    title: 'Confirm Delivery with Client',
    description: 'Order marked as delivered. Confirm receipt with client and collect feedback.',
    team: 'SUPPORT',
    priority: 'MEDIUM',
    dueDaysFromNow: 3,
  },
};

function addDays(days) {
  const d = new Date();
  d.setDate(d.getDate() + days);
  return d;
}

function serializeTask(task) {
  const t = task.toObject ? task.toObject() : task;
  return {
    id: t._id,
    taskCode: t.taskCode,
    orderId: t.order?._id || t.order,
    orderCode: t.order?.orderCode || null,
    clientId: t.client?._id || t.client,
    clientName: t.client?.name || null,
    clientCode: t.client?.clientCode || null,
    assignedTo: t.assignedTo ? {
      id: t.assignedTo._id || t.assignedTo,
      name: t.assignedTo.name || null,
      adminCode: t.assignedTo.adminCode || null,
    } : null,
    title: t.title,
    description: t.description,
    team: t.team,
    priority: t.priority,
    dueDate: t.dueDate,
    status: t.status,
    completedAt: t.completedAt,
    completedBy: t.completedBy,
    notes: t.notes,
    autoGenerated: t.autoGenerated,
    triggerStatus: t.triggerStatus,
    createdAt: t.createdAt,
    updatedAt: t.updatedAt,
  };
}

async function listTasks({ orderId, clientId, status, team, priority, assignedTo, page = 1, limit = 20, sortBy = 'createdAt', sortDir = 'desc' } = {}) {
  const filter = {};
  if (orderId) filter.order = orderId;
  if (clientId) filter.client = clientId;
  if (status) filter.status = status;
  if (team) filter.team = team;
  if (priority) filter.priority = priority;
  if (assignedTo) filter.assignedTo = assignedTo;

  const sort = { [sortBy]: sortDir === 'asc' ? 1 : -1 };
  const skip = (page - 1) * limit;

  const [tasks, total] = await Promise.all([
    Task.find(filter)
      .sort(sort)
      .skip(skip)
      .limit(limit)
      .populate('order', 'orderCode')
      .populate('client', 'name clientCode')
      .populate('assignedTo', 'name adminCode'),
    Task.countDocuments(filter),
  ]);

  return {
    tasks: tasks.map(serializeTask),
    total,
    page,
    pages: Math.ceil(total / limit),
  };
}

async function getTask(id) {
  const task = await Task.findById(id)
    .populate('order', 'orderCode status')
    .populate('client', 'name clientCode')
    .populate('assignedTo', 'name adminCode')
    .populate('completedBy', 'name adminCode');
  if (!task) throw AppError.notFound('Task not found.');
  return serializeTask(task);
}

async function createTask(data, actor) {
  const { orderId, title, description, team, priority, dueDate, notes, assignedTo } = data;

  const order = await Order.findById(orderId).select('_id client');
  if (!order) throw AppError.notFound('Order not found.');

  const taskCode = await generateTaskCode();

  const task = await Task.create({
    taskCode,
    order: order._id,
    client: order.client || null,
    assignedTo: assignedTo || null,
    title,
    description,
    team,
    priority: priority || 'MEDIUM',
    dueDate: dueDate || null,
    notes: notes || null,
    status: 'OPEN',
    autoGenerated: false,
  });

  await logAudit({
    actor,
    action: AUDIT_ACTIONS.TASK_CREATED,
    resourceType: 'Task',
    resourceId: task._id,
    metadata: { taskCode, title, team, orderId },
  });

  return serializeTask(task);
}

async function updateTask(id, data, actor) {
  const task = await Task.findById(id);
  if (!task) throw AppError.notFound('Task not found.');

  const allowed = ['title', 'description', 'team', 'priority', 'dueDate', 'notes', 'assignedTo', 'status'];
  for (const key of allowed) {
    if (data[key] !== undefined) task[key] = data[key];
  }

  if (data.status === 'DONE' && !task.completedAt) {
    task.completedAt = new Date();
    task.completedBy = actor._id || actor;
  }

  await task.save();

  await logAudit({
    actor,
    action: AUDIT_ACTIONS.TASK_UPDATED,
    resourceType: 'Task',
    resourceId: task._id,
    metadata: { taskCode: task.taskCode, changes: data },
  });

  return serializeTask(task);
}

async function completeTask(id, actor) {
  const task = await Task.findById(id);
  if (!task) throw AppError.notFound('Task not found.');
  if (task.status === 'DONE') throw AppError.conflict('Task is already completed.');
  if (task.status === 'CANCELLED') throw AppError.conflict('Cannot complete a cancelled task.');

  task.status = 'DONE';
  task.completedAt = new Date();
  task.completedBy = actor._id || actor;
  await task.save();

  await logAudit({
    actor,
    action: AUDIT_ACTIONS.TASK_COMPLETED,
    resourceType: 'Task',
    resourceId: task._id,
    metadata: { taskCode: task.taskCode },
  });

  return serializeTask(task);
}

// Called by orderStateMachine after every status transition.
// Creates auto-task(s) for the new status if configured. Never throws.
async function autoCreateTasksForStatus(order, toStatus) {
  const def = AUTO_TASKS[toStatus];
  if (!def) return;

  try {
    const taskCode = await generateTaskCode();
    await Task.create({
      taskCode,
      order: order._id,
      client: order.client || null,
      assignedTo: order.assignedAdmin || null,
      title: def.title,
      description: def.description,
      team: def.team,
      priority: def.priority,
      dueDate: addDays(def.dueDaysFromNow),
      status: 'OPEN',
      autoGenerated: true,
      triggerStatus: toStatus,
    });
  } catch (err) {
    // Auto-task creation failures must never block order status transitions
    const logger = require('../../utils/portal/logger');
    logger.error(`[task.service] autoCreateTasksForStatus failed for ${toStatus}: ${err.message}`);
  }
}

async function getWorkflowStats() {
  const now = new Date();
  const todayEnd = new Date(now);
  todayEnd.setHours(23, 59, 59, 999);

  const [open, inProgress, overdue, dueToday, byTeam] = await Promise.all([
    Task.countDocuments({ status: 'OPEN' }),
    Task.countDocuments({ status: 'IN_PROGRESS' }),
    Task.countDocuments({ status: { $in: ['OPEN', 'IN_PROGRESS'] }, dueDate: { $lt: now } }),
    Task.countDocuments({ status: { $in: ['OPEN', 'IN_PROGRESS'] }, dueDate: { $gte: now, $lte: todayEnd } }),
    Task.aggregate([
      { $match: { status: { $in: ['OPEN', 'IN_PROGRESS'] } } },
      { $group: { _id: '$team', count: { $sum: 1 } } },
    ]),
  ]);

  const teamBreakdown = {};
  for (const row of byTeam) teamBreakdown[row._id] = row.count;

  return { open, inProgress, overdue, dueToday, teamBreakdown };
}

module.exports = { listTasks, getTask, createTask, updateTask, completeTask, autoCreateTasksForStatus, getWorkflowStats };
