/**
 * Named audit actions. Prevents typo-prone free-text action strings
 * scattered through the codebase.
 */
const AUDIT_ACTIONS = Object.freeze({
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILED: 'LOGIN_FAILED',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  LOGOUT: 'LOGOUT',
  LOGOUT_ALL: 'LOGOUT_ALL',
  TOKEN_REFRESH: 'TOKEN_REFRESH',
  TOKEN_REUSE_DETECTED: 'TOKEN_REUSE_DETECTED',
  PASSWORD_CHANGED: 'PASSWORD_CHANGED',
  PASSWORD_RESET_REQUESTED: 'PASSWORD_RESET_REQUESTED',
  PASSWORD_RESET_COMPLETED: 'PASSWORD_RESET_COMPLETED',
  PROFILE_UPDATED: 'PROFILE_UPDATED',
  ACCOUNT_DISABLED: 'ACCOUNT_DISABLED',

  ADMIN_CREATED: 'ADMIN_CREATED',
  ADMIN_UPDATED: 'ADMIN_UPDATED',
  ADMIN_ENABLED: 'ADMIN_ENABLED',
  ADMIN_DISABLED: 'ADMIN_DISABLED',
  ADMIN_SUSPENDED: 'ADMIN_SUSPENDED',
  ADMIN_ROLE_CHANGED: 'ADMIN_ROLE_CHANGED',
  ADMIN_PERMISSIONS_CHANGED: 'ADMIN_PERMISSIONS_CHANGED',
  ADMIN_SCOPE_CHANGED: 'ADMIN_SCOPE_CHANGED',
  ADMIN_PASSWORD_RESET: 'ADMIN_PASSWORD_RESET',
  ADMIN_SESSIONS_REVOKED: 'ADMIN_SESSIONS_REVOKED',

  CLIENT_CREATED: 'CLIENT_CREATED',
  CLIENT_UPDATED: 'CLIENT_UPDATED',
  CLIENT_STATUS_CHANGED: 'CLIENT_STATUS_CHANGED',
  CLIENT_ASSIGNED: 'CLIENT_ASSIGNED',
  CLIENT_REASSIGNED: 'CLIENT_REASSIGNED',
  CLIENT_UNASSIGNED: 'CLIENT_UNASSIGNED',
  CLIENT_ARCHIVED: 'CLIENT_ARCHIVED',
  CLIENT_AUTH_STATUS_CHANGED: 'CLIENT_AUTH_STATUS_CHANGED',
  CLIENT_PROFILE_VIEWED: 'CLIENT_PROFILE_VIEWED',
  CLIENT_SELF_PROFILE_UPDATED: 'CLIENT_SELF_PROFILE_UPDATED',

  ORDER_CREATED: 'ORDER_CREATED',
  ORDER_UPDATED: 'ORDER_UPDATED',
  ORDER_ASSIGNED: 'ORDER_ASSIGNED',
  ORDER_REASSIGNED: 'ORDER_REASSIGNED',
  ORDER_UNASSIGNED: 'ORDER_UNASSIGNED',
  ORDER_STATUS_CHANGED: 'ORDER_STATUS_CHANGED',
  ORDER_CANCELLED: 'ORDER_CANCELLED',
  ORDER_CLOSED: 'ORDER_CLOSED',
  ORDER_PAYMENT_STATUS_CHANGED: 'ORDER_PAYMENT_STATUS_CHANGED',
  ORDER_DEV_STATUS_OVERRIDE: 'ORDER_DEV_STATUS_OVERRIDE',

  PAYMENT_UPDATED: 'PAYMENT_UPDATED',
  PAYMENT_ORDER_CREATED: 'PAYMENT_ORDER_CREATED',
  PAYMENT_VERIFIED: 'PAYMENT_VERIFIED',
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  PAYMENT_WEBHOOK_RECEIVED: 'PAYMENT_WEBHOOK_RECEIVED',
  PAYMENT_REFUND_REQUESTED: 'PAYMENT_REFUND_REQUESTED',
  PAYMENT_REFUNDED: 'PAYMENT_REFUNDED',
  PAYMENT_RECONCILED: 'PAYMENT_RECONCILED',

  INVOICE_GENERATED: 'INVOICE_GENERATED',
  INVOICE_EMAIL_RESENT: 'INVOICE_EMAIL_RESENT',
  INVOICE_REGENERATED: 'INVOICE_REGENERATED',
  INVOICE_DELETED: 'INVOICE_DELETED',
  INVOICE_DOWNLOADED: 'INVOICE_DOWNLOADED',

  SETTING_UPDATED: 'SETTING_UPDATED',

  KYC_UPLOADED: 'KYC_UPLOADED',
  KYC_DOCUMENT_REPLACED: 'KYC_DOCUMENT_REPLACED',
  KYC_VIEWED: 'KYC_VIEWED',
  KYC_DOWNLOADED: 'KYC_DOWNLOADED',
  KYC_DOCUMENT_VERIFIED: 'KYC_DOCUMENT_VERIFIED',
  KYC_DOCUMENT_REJECTED: 'KYC_DOCUMENT_REJECTED',
  // Part 5 enterprise KYC addition - see KYC_DOCUMENT_STATUS.NEED_REUPLOAD.
  KYC_DOCUMENT_REUPLOAD_REQUESTED: 'KYC_DOCUMENT_REUPLOAD_REQUESTED',
  KYC_SUBMITTED: 'KYC_SUBMITTED',
  KYC_REVIEW_STARTED: 'KYC_REVIEW_STARTED',
  KYC_VERIFIED: 'KYC_VERIFIED',
  KYC_REJECTED: 'KYC_REJECTED',
  KYC_DELETED: 'KYC_DELETED',
  KYC_DOCUMENT_DELETED: 'KYC_DOCUMENT_DELETED',
  KYC_DELETION_FAILED: 'KYC_DELETION_FAILED',

  // Wave 2 (admin/super-admin KYC workflows) additions - all additive.
  KYC_ORDER_APPROVED: 'KYC_ORDER_APPROVED', // order-level "approve complete KYC"
  KYC_ORDER_REJECTED: 'KYC_ORDER_REJECTED', // order-level "reject complete KYC"
  KYC_FORCE_APPROVED: 'KYC_FORCE_APPROVED', // Super Admin force-approve, bypasses KYC_VERIFICATION guard
  KYC_FORCE_REJECTED: 'KYC_FORCE_REJECTED', // Super Admin force-reject, bypasses KYC_VERIFICATION guard
  KYC_REVIEWER_ASSIGNED: 'KYC_REVIEWER_ASSIGNED',
  KYC_COMMENT_ADDED: 'KYC_COMMENT_ADDED',
  KYC_BULK_EXPORTED: 'KYC_BULK_EXPORTED',

  SERVICE_CREATED: 'SERVICE_CREATED',
  SERVICE_UPDATED: 'SERVICE_UPDATED',
  SERVICE_STATUS_CHANGED: 'SERVICE_STATUS_CHANGED',
  SERVICE_ARCHIVED: 'SERVICE_ARCHIVED',
  SERVICE_FORM_UPDATED: 'SERVICE_FORM_UPDATED',
  SERVICE_DOCUMENT_REQUIREMENTS_UPDATED: 'SERVICE_DOCUMENT_REQUIREMENTS_UPDATED',
  SERVICE_PRICING_UPDATED: 'SERVICE_PRICING_UPDATED',
  SERVICE_VISIBILITY_CHANGED: 'SERVICE_VISIBILITY_CHANGED',

  ACCOUNT_STATUS_CHANGED: 'ACCOUNT_STATUS_CHANGED',

  COMMUNICATION_DISPATCHED: 'COMMUNICATION_DISPATCHED',
  COMMUNICATION_FAILED: 'COMMUNICATION_FAILED',

  SUPPORT_TICKET_CREATED: 'SUPPORT_TICKET_CREATED',
  SUPPORT_TICKET_REPLIED: 'SUPPORT_TICKET_REPLIED',
  SUPPORT_TICKET_UPDATED: 'SUPPORT_TICKET_UPDATED',

  TASK_CREATED: 'TASK_CREATED',
  TASK_UPDATED: 'TASK_UPDATED',
  TASK_COMPLETED: 'TASK_COMPLETED',
  TASK_CANCELLED: 'TASK_CANCELLED',

  SECURITY_EVENT: 'SECURITY_EVENT',
});

module.exports = { AUDIT_ACTIONS };
