/**
 * Centralized communication event catalogue. Each event maps to the
 * channels/templates defined in communication/templates.js. Only events
 * actually dispatched somewhere in the codebase are listed here.
 */
const COMMUNICATION_EVENT = Object.freeze({
  ORDER_CREATED: 'ORDER_CREATED',
  ORDER_PAYMENT_PENDING: 'ORDER_PAYMENT_PENDING',
  ORDER_PAYMENT_CONFIRMED: 'ORDER_PAYMENT_CONFIRMED',
  ORDER_PAYMENT_FAILED: 'ORDER_PAYMENT_FAILED',
  ORDER_ASSIGNED: 'ORDER_ASSIGNED',
  ORDER_STATUS_CHANGED: 'ORDER_STATUS_CHANGED',
  ORDER_CANCELLED: 'ORDER_CANCELLED',
  ORDER_COMPLETED: 'ORDER_COMPLETED',
  ORDER_CLOSED: 'ORDER_CLOSED',

  KYC_SUBMITTED: 'KYC_SUBMITTED',
  KYC_REJECTED: 'KYC_REJECTED',
  KYC_VERIFIED: 'KYC_VERIFIED',
  KYC_DOCUMENT_REJECTED: 'KYC_DOCUMENT_REJECTED',

  PAYMENT_REFUNDED: 'PAYMENT_REFUNDED',
});

const ALL_COMMUNICATION_EVENTS = Object.values(COMMUNICATION_EVENT);

module.exports = { COMMUNICATION_EVENT, ALL_COMMUNICATION_EVENTS };
