/**
 * Centralized communication event catalogue. Each event maps to the
 * channels/templates defined in communication/templates.js. Only events
 * actually dispatched somewhere in the codebase are listed here.
 */
const COMMUNICATION_EVENT = Object.freeze({
  ORDER_CREATED: 'ORDER_CREATED',
  ORDER_PAYMENT_PENDING: 'ORDER_PAYMENT_PENDING',
  ORDER_PAYMENT_CONFIRMED: 'ORDER_PAYMENT_CONFIRMED',
  ORDER_PAYMENT_FAILED: 'ORDER_PAYMENT_FAILED',
  ORDER_ASSIGNED: 'ORDER_ASSIGNED',
  ORDER_STATUS_CHANGED: 'ORDER_STATUS_CHANGED',
  ORDER_CANCELLED: 'ORDER_CANCELLED',
  ORDER_COMPLETED: 'ORDER_COMPLETED',
  ORDER_CLOSED: 'ORDER_CLOSED',

  KYC_SUBMITTED: 'KYC_SUBMITTED',
  KYC_REJECTED: 'KYC_REJECTED',
  KYC_VERIFIED: 'KYC_VERIFIED',
  KYC_DOCUMENT_REJECTED: 'KYC_DOCUMENT_REJECTED',
  // Wave 2 addition (additive) - see kyc.service.js's requestReupload.
  KYC_DOCUMENT_NEED_REUPLOAD: 'KYC_DOCUMENT_NEED_REUPLOAD',

  PAYMENT_REFUNDED: 'PAYMENT_REFUNDED',

  CLIENT_WELCOME: 'CLIENT_WELCOME',
  ADMIN_CREATED: 'ADMIN_CREATED',
  CLIENT_ASSIGNED_ADMIN: 'CLIENT_ASSIGNED_ADMIN',
  ADMIN_CLIENT_ASSIGNED: 'ADMIN_CLIENT_ASSIGNED',
  INVOICE_GENERATED: 'INVOICE_GENERATED',

  DOCUMENT_REQUESTED: 'DOCUMENT_REQUESTED',
  DOCUMENT_FULFILLED: 'DOCUMENT_FULFILLED',

  // Wave 2 addition - see kyc.service.js's assignReviewer(), which
  // previously only fired an in-app notification with no email.
  KYC_REVIEWER_ASSIGNED: 'KYC_REVIEWER_ASSIGNED',

  // Phase 11 (smart notification) additions - additive only.
  ORDER_PAID_AWAITING_ASSIGNMENT: 'ORDER_PAID_AWAITING_ASSIGNMENT',
  VIRUS_DETECTED: 'VIRUS_DETECTED',
});

const ALL_COMMUNICATION_EVENTS = Object.values(COMMUNICATION_EVENT);

module.exports = { COMMUNICATION_EVENT, ALL_COMMUNICATION_EVENTS };
