const COMMUNICATION_CHANNEL = Object.freeze({
  EMAIL: 'EMAIL',
  WHATSAPP: 'WHATSAPP',
  SMS: 'SMS',
});

const ALL_COMMUNICATION_CHANNELS = Object.values(COMMUNICATION_CHANNEL);

module.exports = { COMMUNICATION_CHANNEL, ALL_COMMUNICATION_CHANNELS };
