/**
 * Stable machine-readable error codes used in API error responses.
 * Frontend code should branch on `code`, never on the human `message`
 * string, since messages may be reworded.
 */
const ERROR_CODES = Object.freeze({
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  ACCOUNT_DISABLED: 'ACCOUNT_DISABLED',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_INVALID: 'TOKEN_INVALID',
  FORBIDDEN: 'FORBIDDEN',
  PERMISSION_DENIED: 'PERMISSION_DENIED',
  DATA_SCOPE_DENIED: 'DATA_SCOPE_DENIED',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  CANNOT_REMOVE_LAST_SUPER_ADMIN: 'CANNOT_REMOVE_LAST_SUPER_ADMIN',
  INVALID_STATE_TRANSITION: 'INVALID_STATE_TRANSITION',
  RATE_LIMITED: 'RATE_LIMITED',
  FEATURE_NOT_IMPLEMENTED: 'FEATURE_NOT_IMPLEMENTED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
});

module.exports = { ERROR_CODES };
