const NOTIFICATION_SEVERITY = Object.freeze({
  INFO: 'INFO',
  SUCCESS: 'SUCCESS',
  WARNING: 'WARNING',
  CRITICAL: 'CRITICAL',
});

const ALL_NOTIFICATION_SEVERITIES = Object.values(NOTIFICATION_SEVERITY);

module.exports = { NOTIFICATION_SEVERITY, ALL_NOTIFICATION_SEVERITIES };
