const REPORT_PERIOD = Object.freeze({
  TODAY: 'TODAY',
  YESTERDAY: 'YESTERDAY',
  LAST_7_DAYS: 'LAST_7_DAYS',
  LAST_30_DAYS: 'LAST_30_DAYS',
  THIS_MONTH: 'THIS_MONTH',
  LAST_MONTH: 'LAST_MONTH',
  THIS_YEAR: 'THIS_YEAR',
  CUSTOM: 'CUSTOM',
});

const ALL_REPORT_PERIODS = Object.values(REPORT_PERIOD);

module.exports = { REPORT_PERIOD, ALL_REPORT_PERIODS };
