const SERVICE_CATEGORY = Object.freeze({
  WEBSITE: 'WEBSITE',
  WHATSAPP: 'WHATSAPP',
  CRM: 'CRM',
  HRMS: 'HRMS',
  SOFTWARE: 'SOFTWARE',
  DIGITAL_MARKETING: 'DIGITAL_MARKETING',
  OTHER: 'OTHER',
});

const ALL_SERVICE_CATEGORIES = Object.values(SERVICE_CATEGORY);

module.exports = { SERVICE_CATEGORY, ALL_SERVICE_CATEGORIES };
